-- NotifikacijaTip: nove vrednosti za logistika workflow
ALTER TYPE "NotifikacijaTip" ADD VALUE IF NOT EXISTS 'RN_PRIHVACEN_LOGISTIKA';
ALTER TYPE "NotifikacijaTip" ADD VALUE IF NOT EXISTS 'PRIPREMA_POSLATA';
ALTER TYPE "NotifikacijaTip" ADD VALUE IF NOT EXISTS 'KOLORNA_PROBA_NA_OVERAVANJU';
ALTER TYPE "NotifikacijaTip" ADD VALUE IF NOT EXISTS 'PROBA_ODOBRENA';
ALTER TYPE "NotifikacijaTip" ADD VALUE IF NOT EXISTS 'PROBA_KOREKCIJA';
ALTER TYPE "NotifikacijaTip" ADD VALUE IF NOT EXISTS 'STAMPA_GOTOVA';
ALTER TYPE "NotifikacijaTip" ADD VALUE IF NOT EXISTS 'MONTAZA_ZAVRSENA';
